/*room*/
create table
  public.room (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    room_name text not null,
    constraint Room_pkey primary key (id)
  ) tablespace pg_default;

/*users*/
  create table
  public.users (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    name text not null,
    "isSuper" boolean not null default false,
    room_id bigint null,
    constraint Users_pkey primary key (id),
    constraint users_room_id_fkey foreign key (room_id) references room (id)
  ) tablespace pg_default;

  /*event*/
create table
  public.event (
    id bigint generated by default as identity,
    name text not null,
    date date not null,
    time time without time zone null,
    constraint Event_pkey primary key (id)
  ) tablespace pg_default;

  
/*calendar*/
create table
  public.calendar (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    name text null,
    room_id bigint null,
    user_id bigint null,
    constraint Calendar_pkey primary key (id),
    constraint calendar_room_id_fkey foreign key (room_id) references room (id),
    constraint calendar_user_id_fkey foreign key (user_id) references users (id)
  ) tablespace pg_default;


/*chores*/
create table
  public.chores (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    chore_name text not null,
    assigned_user_id bigint not null,
    completed boolean not null,
    constraint chores_pkey primary key (id),
    constraint chores_assigned_user_id_fkey foreign key (assigned_user_id) references users (id)
  ) tablespace pg_default;

/*split*/
  create table
  public.split (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    name text null,
    price real null,
    quantity integer null,
    user_added bigint null,
    constraint split_pkey primary key (id),
    constraint split_user_added_fkey foreign key (user_added) references users (id)
  ) tablespace pg_default;

